import type { Metadata } from "next";
import Link from "next/link";
import { getDataUsers } from "@/api";

export const metadata: Metadata = {
  title: "Users | Next App",
  description: "Generated by create next app",
};

export default async function Users() {
  const users = await getDataUsers();

  return (
    <div className="bg-slate-700 flex-grow">
      <div className="container m-auto p-4">
        <h1 className="text-2xl font-semibold underline mt-12 mb-4">
          All users:
        </h1>
        <ul className="flex flex-wrap">
          {users.map((user, index) => {
            return (
              <li
                key={user.id}
                className="w-full md:w-1/2 my-2 transition-colors duration-300 hover:text-blue-400"
              >
                <Link className="" href={`/users/${user.id}`}>
                  {index + 1}. {user.name} - {user.username}
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}
