import type { Metadata } from "next";
import Link from "next/link";
import { getDataPosts } from "@/api";

export const metadata: Metadata = {
  title: "Posts | Next App",
  description: "Generated by create next app",
};

export default async function Posts() {
  const posts = await getDataPosts();

  return (
    <div className="bg-slate-700 flex-grow">
      <div className="container m-auto p-4">
        <h1 className="text-2xl font-semibold underline mt-12 mb-4">
          All posts:
        </h1>
        <ul className="flex flex-wrap">
          {posts.map((post, index) => {
            return (
              <li
                key={post.id}
                className="w-full md:w-1/2 my-2 transition-colors duration-300 hover:text-blue-400"
              >
                <Link className="" href={`/posts/${post.id}`}>
                  {index + 1}. {post.title}
                </Link>
              </li>
            );
          })}
        </ul>
      </div>
    </div>
  );
}
